core/account/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .forms import UserLoginForm
from . import views

app_name = 'account'

urlpatterns = [
    path('profile/user_history/', views.user_history, name='user_history'),
    path('profile/confirmation/', TemplateView.as_view(template_name='account/confirmation.html'), name='confirmation'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', form_class=UserLoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('add_seller/', views.add_seller, name='add_seller'),    
]

core/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('update/', views.cart_update, name='cart_update'),
    path('del/', views.cart_del, name='cart_del'),
    path('add/', views.cart_add, name='cart_add'),
    path('', views.cart_summary, name='cart_summary'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')), 
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('add/', views.add, name='add'),
]

core/payment/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'payment'

urlpatterns = [
    path('confirm_pay/', TemplateView.as_view(template_name='payment/confirm_pay.html'), name='confirm_pay'),
    path('', views.CartView, name='cartview'), 
]

core/payment/models.py
from django.db import models

# Create your models here.

core/payment/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
import random
import string

from cart.cart import Cart

@login_required
def CartView(request):
    """ 
        Quando un utente vuole fare il checkout 
        viene redirezionato con i giusti dati nella pagina per il pagamento. 
    """

    cart = Cart(request)
    tot  = str(cart.get_tot_price())
    tot  = int(tot.replace('.', ''))
    key  = ''.join(random.choice(string.printable) for _ in range(20)) # Creates the order key
    ctx  = {'client_secret': key,}

    return render(request, 'payment/home.html', context=ctx)


def order_placed(request):
    """ Dopo ogni pagamento viene pulito il carrello. """
    
    cart = Cart(request)
    cart.clear()

    return render(request, 'account/profile.html')

core/templates/payment/confirm_pay.html
{% extends '../store/base.html' %}


{% block title %}Confirm payment{% endblock title %}


{% block content %}
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-md-12">
                <div class="mt-5 py-5 login d-flex align-items-center">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-lg-6 mx-auto">
                                <div class="text-center alert alert-success" role="alert">
                                    <h2 class="mb-4">Payed successfully!</h2>
                                    <h5 class="mb-4">Thank you for choosing MangaStore</h5>

                                    <a link href="{% url "account:user_history" %}">See your past orders here</a>
                                </div>       
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/payment/home.html
{% extends '../store/base.html' %}
{% block title %}Payment{% endblock title %} 

{% block content %}
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="py-5 mt-4 col-md-12">
                <div class="login mt-5 py-5 login d-flex align-items-center">
                    <div class="container ">          
                        {% csrf_token %}

                        {% if user.is_seller or user.is_staff %}
                            <div class="alert alert-danger text-center" type="alert">
                                Seller or staff member can't buy products.
                                <br>
                                Please login with another user account.
                                <br>
                                Note: after the logout the cart will be deleted.
                            </div>
                        {% else %}
                            <h3 class="text-center">Payment</h3>
                            <div class="row">
                                <div id="payment-form" class="col-12 col-lg-6 mx-auto">                        
                                    <form class="text-center">
                                        <label for="card-element">Credit or debit card</label>
                                        <input type="number" class="form-control"  placeholder="" required>
                                
                                        <div>
                                            <button id="submit" class="btn btn-outline-success btn-block py-2 mb-4 mt-5" data-secret="{{ client_secret }}">
                                            Pay
                                            </button>
                                        </div>
                                    </form>  
                                </div>
                            </div>
                        {% endif %}                                                   
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var form = document.getElementById('payment-form');

        form.addEventListener('submit', function(e)
        {
            e.preventDefault();
            var el = document.getElementById('submit');

            $.ajax({ type: 'POST',    
                url: '{% url "orders:add" %}',
                data: { order_key: el.getAttribute('data-secret'),
                    csrfmiddlewaretoken: "{{ csrf_token }}",
                    action: 'post' },        
                success: function (json){ 
                    window.location.replace('{% url "payment:confirm_pay" %}')},
                
                error: function (xhr, errmsg, err){}
                });
        })
    </script>
{% endblock content %}