core/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('update/', views.cart_update, name='cart_update'),
    path('del/', views.cart_del, name='cart_del'),
    path('add/', views.cart_add, name='cart_add'),
    path('', views.cart_summary, name='cart_summary'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')), 
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/payment/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'payment'

urlpatterns = [
    path('confirm_pay/', TemplateView.as_view(template_name='payment/confirm_pay.html'), name='confirm_pay'),
    path('', views.CartView, name='cartview'), 
]

core/cart/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

import random
import string

from .cart import Cart
from store.models import Product


def cart(request):
    """ Ritorna il carrello di una certa sessione. """

    return {'cart': Cart(request)}

def cart_summary(request):
    """ Rendera la lista corrente dei prodotti nel carrello. """

    cart = Cart(request)
    ctx  = { 'cart': cart }
    return render(request, 'cart/summary.html', ctx)

def cart_add(request):
    """ Aggiunge un prodotto nel carrello. """

    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id  = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        cart.add(product=product, qty=product_qty)
        
        tot_qty  = cart.__len__()
        response = JsonResponse({'qty': tot_qty})
        return response


def cart_del(request):
    """ Cancella un prodotto dal carrello. """

    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        cart.delete(product=product_id)

        cartqty  = cart.__len__()
        carttot  = cart.get_tot_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttot})
        return response

def cart_update(request):
    """ Cambia la quantita' di un prodotto nel carrello. """

    cart = Cart(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        qty = int(request.POST.get('productqty'))
        cart.update(product=product_id, qty=qty)

        cartqty  = cart.__len__()
        carttot  = cart.get_tot_price()
        response = JsonResponse({'qty': cartqty, 'subtotal': carttot })
        return response

@login_required
def CartView(request):
    """ Il pagamento avviene tramite l'immisione del numero della carta. """

    cart = Cart(request)
    tot  = str(cart.get_tot_price())
    tot  = tot.replace('.', '')
    tot  = int(tot)

    key  = ''.join(random.choice(string.ascii_lowercase) for _ in range(20))

    ctx  = {'client_secret': key}
    return render(request, 'payment/home.html', context=ctx )

core/templates/cart/summary.html
{% extends '../store/base.html' %}
{% load static %}


{% block title %}Cart summary{% endblock title %}


{% block content %}
    <main class="py-5">
        <div class="container">
            <div class="my-5 pb-3 h4">Shopping cart</div>




            {% for item in cart %}
                {% with product=item.product %}
                    <div data-index="{{ product.id }}" class="row mb-4 border product-item">
                        <div class="row mb-1">
                            <div class="col-md-9">
                                <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
                                    <div class="col-auto d-none d-lg-block">
                                        <img href="{{ product.get_absolute_url }}" src="{{ product.image.url }}" class="featurette-image img-fluid mx-auto" alt="Responsive image" width="170px"  height="270px" preserveAspectRatio="xMidYMid slice" focusable="false"></img>
                                    </div>
                                    <div class="col p-4 d-flex flex-column position-static">
                                        <h3 class="mb-0">{{ product.title|title }}</h3>
                                        <div class="mb-1 text-muted">{{ product.author|title }}</div>
    
                                        <div class="border">
                                            <div class="col border-bottom">
                                                <div class="row p-3">
                                                    <div class="col-6">Prezzo</div>
                                                    <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }}€</span></div>
                                                </div>
                                            </div>
                
                                            <div class="col">
                                                <div class="row p-3">
                                                    <div class="col-6">
                                                        <label for="select{{product.id}}">Qty</label>
                                                        <select id="select{{product.id}}">
                                                            {% for i in product.get_qty %}
                                                                {% if i|add:1 == item.qty %} <option selected="{{item.qty}}"> {{ item.qty}} </option>
                                                                {% else %}  <option value="{{i|add:1}}">{{ i|add:1 }}</option>
                                                                {% endif %}
                                                            {% endfor %}  
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="row-6">
                                                    <button type="button" id="update-button" data-index="{{ product.id }}" class="btn btn-secondary btn-sm update-button" >Update</button>
                                                    <button type="button" id="delete-button" data-index="{{ product.id }}" class="btn btn-secondary btn-sm delete-button" >Delete</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>     
                                </div>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
            
            {% if cart.get_tot_price %}
                <div class="col-9 text-end">       
                    <div class="h3 fw-bold">Total price: <a id="subtotal">{{ cart.get_tot_price }}</a>€</div>
                    <a role="button" href="{% url "payment:cartview" %}" class="btn btn-outline-success fw-bold" type="button">Checkout</a>
                </div>
            {% endif %}          
        </div>
    </main>

    <script>
        $(document).on('click', '.delete-button', function (e)
        {
            e.preventDefault();
            var id = $(this).data('index');
            $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_del" %}',
                    data: { productid: $(this).data('index'),
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                            action: 'post' },
                    success: function (json){ 
                            $('.product-item[data-index="' + id + '"]').remove(); 
                            document.getElementById("subtotal").innerHTML = json.subtotal ;
                            document.getElementById("cartqty").innerHTML = json.qty; },
                    error: function (xhr, errmsg, err){}
                    });
        })

        $(document).on('click', '.update-button', function (e)
        {
            e.preventDefault();
            var id = $(this).data('index');
            $.ajax({
                    type: 'POST',
                    url: '{% url "cart:cart_update" %}',
                    data: { productid: $(this).data('index'),
                            productqty: $('#select' + id + ' option').filter(':selected').val(),
                            csrfmiddlewaretoken: "{{ csrf_token }}",
                            action: 'post' },
                    success: function (json){ 
                        document.getElementById("subtotal").innerHTML = json.subtotal;
                        document.getElementById("cartqty").innerHTML = json.qty; },
                    error: function (xhr, errmsg, err){ }
                    });
        })
    </script>
{% endblock content %}