core/account/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

from .forms import UserLoginForm
from . import views

app_name = 'account'

urlpatterns = [
    path('profile/user_history/', views.user_history, name='user_history'),
    path('profile/confirmation/', TemplateView.as_view(template_name='account/confirmation.html'), name='confirmation'),
    path('profile/delete/', views.delete, name='delete'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html', form_class=UserLoginForm), name='login'),
    path('profile/', views.profile, name='profile'),
    path('registration/', views.registration, name='registration'),
    path('add_seller/', views.add_seller, name='add_seller'),    
]

core/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('update/', views.cart_update, name='cart_update'),
    path('del/', views.cart_del, name='cart_del'),
    path('add/', views.cart_add, name='cart_add'),
    path('', views.cart_summary, name='cart_summary'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')), 
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('search/', views.search, name='search'),
    path('create_product/', views.create_product ,name="create_product"),
    path('create_category/', views.create_category ,name="create_category"),
    path('<slug:slug>/', views.product_detail, name='product_detail'),  
    path('shop/<slug:slug>/', views.category_list, name='category_list'),
    path('rating/create_review/<slug:slug>/', views.create_review, name="create_review"),
]

core/store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.core.validators import MinValueValidator


class Category(models.Model):
    """ Rappresenta la categoria di un certo prodotto. """

    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories' 

    def get_absolute_url(self):
        """ Ritorna la lista dei prodotti per una certa categoria. """

        return reverse_lazy('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    """ Rappresenta un prodotto vendibile sull'e-commerce. """

    category    = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    title       = models.CharField(max_length=255)
    author      = models.CharField(max_length=255, default='Not found')
    description = models.TextField(blank=True)
    available   = models.PositiveIntegerField(default=1, validators=[MinValueValidator(0)])
    image       = models.ImageField(upload_to='images/', default='default.png') # salva il link nel database
    slug        = models.SlugField(max_length=255)
    price       = models.DecimalField(max_digits=4, decimal_places=2, default=4.50, validators=[MinValueValidator(1)])
    in_stock    = models.BooleanField(default=True)
    is_active   = models.BooleanField(default=True)
    created     = models.DateTimeField(auto_now_add=True) 
    updated     = models.DateTimeField(auto_now=True) 

    class Meta:
        ordering = ('-created',)

    def get_qty(self):
        """ Ritorna la quantita disponibile di un prodotto.  """

        return range(self.available)

    def get_absolute_url(self):
        """ Ritorna l'url di un prodotto per vederne il dettaglio. """

        return reverse_lazy('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


RATE_CHOICES = [(1, '1 - Trash'), (2, '2 - Bad'), (3, '3 - Ok'), (4, '4 - Nice'), (5, '5 - Perfect')]

class Review(models.Model):
    """ Rappresenta una revisione. """
    
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date    = models.DateTimeField(auto_now_add=True)
    text    = models.TextField(blank=True)
    rate    = models.PositiveIntegerField(choices=RATE_CHOICES)
   
   
    def __str__(self):
        return self.text

core/store/forms.py
from django import forms

from .models import Category, Product, Review, RATE_CHOICES


class AddCategoryForm(forms.ModelForm):
    """ Reppresenta i campi da riempire per  creare una nuova Category """

    name = forms.CharField(label='Enter name', help_text='required', required=True)

    class Meta:
        model  = Category
        fields = {'name'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Name'})



class AddProductForm(forms.ModelForm):
    """ Rappresenta i campi da riempire per aggiungere un Product. """

    category    = forms.ModelChoiceField(queryset=Category.objects.all())
    title       = forms.CharField(label='Enter title', max_length=255, help_text='Required')
    author      = forms.CharField(initial="Not found", max_length=255, required=False)
    description = forms.Textarea()
    image       = forms.ImageField(initial="images/default.png")
    available   = forms.IntegerField(initial=1)
    price       = forms.DecimalField(max_digits=4, decimal_places=2, initial=4.50)
    
    

    class Meta:
        model  = Product
        fields = {'category', 'title', 'author', 'description', 'image', 'available', 'price'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Category'})
        self.fields['title'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Title'})
        self.fields['author'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Author'})
        self.fields['available'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Available'})
        self.fields['price'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Price'})



class AddReviewForm(forms.ModelForm):
    """ Rappresenta come compilare i campi per creare una Review. """

    text = forms.Textarea()
    rate = forms.ChoiceField(choices=RATE_CHOICES, required=True)

    class Meta:
        model  = Review
        fields = {'text', 'rate'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Text'})
        self.fields['rate'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Rate'})

core/store/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Avg
import re

from account.models import UserBase
from orders.models import Order, OrderItem
from .forms import AddProductForm, AddCategoryForm, AddReviewForm
from .models import Category, Product, Review


def categories(request):
    """ Ritorna tutte le categorie nel database. """

    return { 'categories': Category.objects.all() }

def product_all(request): 
    """ 
        Ritorna tutti i prodotti nel database.
        Serve per la home page.
    """

    products = Product.objects.all()
    ctx = { 'products': products, 'recommend': recommend(request) }
    return render(request, template_name='store/home.html', context=ctx)

def all_reviews(request, slug):
    """ Ritorna le review per un certo prodotto """

    prod = Product.objects.get(slug=slug)
    reviews = Review.objects.filter(product=prod)
    
    
    ctx = {'reviews': reviews}
    return ctx

def product_detail(request, slug):
    """ 
        Ritorna in dettaglio un singolo prodotto.
        Oltre agli attributi di Product vengono passate le review di quel prodotto. 
    """

    product = get_object_or_404(Product, slug=slug)
    ctx = all_reviews(request=request,slug=slug)

    ctx.update({ 'product': product })
    return render(request, 'store/products/single.html', context=ctx)

def category_list(request,slug):
    """ Ritorna la lista di prodotti appartenenti a quella categoria. """

    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category)

    ctx = { 'category': category, 'products': products }
    return render(request, 'store/products/category.html', context=ctx)

@login_required
def create_product(request):
    """ 
        Crea un nuovo prodotto.
        Se invece il titolo e' di un prodotto gia' esistente allora ne cambia i dati.
        Solo un membro dello staff o dei venditori(seller) possono farlo.
        Se l'utente non appartiene ad uno dei due tipi di membro viene mandato alla home page.
    """  

    if not (request.user.is_staff or request.user.is_seller):
        return redirect('/')

    if request.method == 'POST':
        prodform = AddProductForm(request.POST, request.FILES)
        
        if prodform.is_valid():
            slug = re.sub('\W', '', prodform.cleaned_data['title'].lower())
            
            if not Product.objects.filter(slug=slug).exists():
                Product.objects.create(slug=slug, **prodform.cleaned_data)

            else:
                Product.objects.filter(slug=slug).update(**prodform.cleaned_data)

            if prodform.cleaned_data['available'] > 0:
                Product.objects.filter(slug=slug).update(in_stock=True)
            else:
                Product.objects.filter(slug=slug).update(in_stock=False)
                        
            return redirect('/')
    else:
        prodform = AddProductForm()
  
    return render(request, 'store/products/createprod.html', { 'form': prodform } )

@login_required
def create_category(request):
    """ 
        Crea una nuova categoria.
        Se esiste gia una categoria con quel nome allora redirecta l'utente alla home page.
        Come per create_product, solo un membro dello staff o un seller puo' creare nuove categorie.
    """

    if not (request.user.is_staff or request.user.is_seller):
        return redirect('/')

    if request.method == 'POST':
        catform = AddCategoryForm(request.POST)
        
        if catform.is_valid():
            name = catform.cleaned_data['name']
            slug = re.sub('\W', '', name.lower())
            
            if not Category.objects.filter(slug=slug).exists():
                Category.objects.create(slug=slug, name=name)
            
            return redirect('/')
    else:
        catform = AddCategoryForm()
  
    return render(request, 'store/products/createcat.html', { 'form': catform } )

@login_required
def create_review(request, slug):
    """ 
        Crea una nuova revisione.
        Solo un utente normalmente loggato puo' lasciare una review.
        Se un membro dello staff o un seller provano a farne una allora verranno redirezionati nella home page.
    """
        
    if request.user.is_staff or request.user.is_seller:
       return redirect('/')

    if request.method == 'POST':
        rateform = AddReviewForm(request.POST)
        
        if rateform.is_valid():
            product = Product.objects.get(slug=slug)
            usr = UserBase.objects.get(username=request.user)
            Review.objects.create(product=product, user=usr, date=datetime.now() ,**rateform.cleaned_data)
            
            return redirect(f'/{slug}/')
    else:
        rateform = AddReviewForm()
  
    return render(request, 'store/rating/home.html', { 'form': rateform, 'slug': slug } )

def search(request):
    """
        Viene fatta una ricerca della parola data in titolo, autore e descrizione per ogni prodotto.
        Viene inoltre cercato se la parola e' all'interno del nome della categoria.
        Se non viene passato nulla allora si viene redirezionati nella homepage.
    """
    
    word = request.GET.get('word')

    if not word :
        return redirect('/')

    prods = Product.objects.filter(slug__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")
    cats  = Category.objects.filter(slug__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")

    for cat in cats:
        prods |= Product.objects.filter(category=cat)

    prods |= Product.objects.filter(author__regex=r"(\w|\W)*( )*" + str(word) + "(\w|\W)*( )*")
    prods |= Product.objects.filter(description__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")

    ctx = { 'category': "Searched: " + word, 'products': prods }
    return render(request, 'store/products/category.html', context=ctx)

@login_required
def recommend(request):
    """
        La raccomandazione viene fatta vedere solo da utenti loggati.
        Per prima cosa vengono cercati tutti i prodotti con una media di piu di 2 stelle.
        Poi viene fatta una ricerca di tutti i prodotti comprati per capirne la categoria preferita
        e passare quindi i prodotti con quella categoria non ancora comprati.
    """

    products = list(Product.objects.filter(in_stock=True))
    prods = set()

    for product in products:
        if Review.objects.filter(product=product).exists():
            if Review.objects.filter(product=product).aggregate(Avg('rate'))['rate__avg'] > 2:
                prods.add(product)

    for order in Order.objects.filter(user=request.user):

        for oi in OrderItem.objects.filter(order=order) :
            p = Product.objects.get(title=oi.product)
                
            for product in Product.objects.filter(category=p.category, in_stock=True):
                prods.add(product)

        for oi in OrderItem.objects.filter(order=order) :
            prods.discard(oi.product)

    prods.discard(None)
    if not prods:
        prods = Product.objects.filter(in_stock=True).order_by('price')
        
    return { 'products': list(prods)[:6] }

core/templates/store/base.html
<!DOCTYPE html>
{% load crispy_forms_tags %} 

<html>
    <head>
        <meta charset="utf-8"/>
       
        <title>{% block title %}MangaStore{% endblock title %}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
        
    </head>

    <body>
        <header> 
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="/">MS</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"></button>
                    
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item dropdown">
                                <a class="nav-link border-0 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Products</a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url "store:product_all" %}">All</a></li>
                                    {% for c in categories %}
                                    <li {% if c.slug == Category.slug %} class="selected" {% endif %}>
                                        <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a> 
                                    </li>
                                    {% endfor %}
                                </ul>
                            </li>
                        </ul>
                    </div> 
                    
                    <form class="d-flex" action="{% url 'store:search' %}" method="GET">
                        <div class="input-group">
                            <input id="word" type="text" class="form-control" placeholder="Search" aria-label="Search" name="word">
                            <input type="submit" value="→" class="btn btn-light"/> 
                        </div>
                    </form>
                         
                    {% if user.is_authenticated %}
                        <a type="button" role="button" href="{% url "account:logout" %}" class="btn btn-outline-secondary border-0 basket-btn">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
                                    <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" /><path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                                </svg>
                            </div>
                            <span class="fs15 fw500">Logout</span>
                        </a>
                    {% else %}
                        <a type="button" role="button" href="{% url "account:login" %}" class="btn btn-outline-secondary border-0 basket-btn">
                            <div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-door-closed" viewBox="0 0 16 16">
                                    <path d="M3 2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v13h1.5a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1H3V2zm1 13h8V2H4v13z" /><path d="M9 9a1 1 0 1 0 2 0 1 1 0 0 0-2 0z" />
                                </svg>
                            </div>
                            <span class="fs15 fw500">Login</span>
                        </a>
                    {% endif %}

                    <a type="button" role="button" href="{% url "account:profile" %}" class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
                                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z" />
                            </svg>
                        </div>
                        <span class="fs15 fw500">Account</span>
                    </a>
                        
                    {% if not user.is_staff and not user.is_seller %}
                        <a type="button" role="button" href="{% url "cart:cart_summary" %}" class="btn btn-secondary">
                            {% with totqty=cart|length %}
                                <div id="cartqty" class="d-inline-flex">
                                    {% if totqty > 0 %} {{ totqty }}
                                    {% else %} 0
                                    {% endif %}
                                </div>
                            {% endwith %}

                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart" viewBox="0 0 16 16">
                                <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </svg>
                        </a>     
                    {% endif %}         
                </div>
            </nav>
        </header>
        
        <div id="content">{% block content %} {% endblock content %}</div>

        
    <footer class="container py-5 footer">
        <hr>
        <div class="row pt-4">
            <div class="col-12 col-md">
                <h2>MangaStore</h2>
                <small class="d-block mb-3 text-muted">&copy; 2022-2022</small>
            </div>
        </div>
    </footer>
    </body>
</html>

core/templates/store/home.html
{% extends './base.html' %}

{% load static %}


{% block title %}MangaStore{% endblock title %}


{% block content %}     
    <main>
        {% if user.is_authenticated %}
            <section class="py-5 text-center container">
                <div class="row py-lg-4">
                    <div class="col-lg-6 col-md-8 mx-auto">
                        <div class="my-1 pt-5 h1 fw-bold">Welcome, {{ user.username }}</div>
                    </div>
                </div>
            </section> 
            
            {% if not user.is_staff and not user.is_seller %}
                <section class="py-1 text-center container">
                    <div class="row py-lg-2">
                        <div class="col-lg-6 col-md-8 mx-auto">
                            <div class="my-1 pt-5 h4 fw-bold">Recommended for you</div>
                        </div>
                    </div>

                    
                </section>
                
                <section class="container row row-cols-1 row-cols-sm-5 row-cols-md-6 g-3">
                    {% for p in recommend.products  %}
                        <div class="col">
                            <div class="card border-0">
                                <div class="card-body">
                                    <p class="card-text">
                                        <a class="text-dark text-decoration-none" href="{{ p.get_absolute_url }}">{{ p.title|title }}</a>
                                        {% if not p.in_stock %} 
                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-exclamation-circle" viewBox="0 0 16 16">
                                                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                                <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                            </svg>
                                        {% endif %}
                                    </p>
                                </div>
                                <img href="{{ p.get_absolute_url }}" src="{{ p.image.url }}" class="featurette-image img-fluid mx-auto" alt="Responsive image" width="170px"  height="270px" preserveAspectRatio="xMidYMid slice" focusable="false"></img>

                            </div>
                        </div>     
                    {% endfor %}  
                </section> 
                
                {% endif %}

        {% else %}
            <section class="py-5 text-center container">
                <div class="row py-lg-4">
                    <div class="col-lg-6 col-md-8 mx-auto">
                        <div class="my-1 pt-5 h1 fw-bold">Wanna read? MangaStore</div>
                        <a href="{% url "account:login" %}" class="lead text-muted">login or register now</a>
                    </div>
                </div>
            </section>  
        {% endif %}
        
      
        <div class="album py-5 bg-light">
            <div class="container">
            <div class="my-5 pb-3 h4">All books</div>
            <div class="row row-cols-1 row-cols-sm-5 row-cols-md-6 g-3">
                {% for p in products %}
                    <div class="col">
                        <div class="card border-0">
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ p.get_absolute_url }}">{{ p.title|title }}</a>
                                    {% if not p.in_stock %} 
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-exclamation-circle" viewBox="0 0 16 16">
                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                        </svg>
                                    {% endif %}
                                </p>
                            </div>
                            <img href="{{ p.get_absolute_url }}" src="{{ p.image.url }}" class="featurette-image img-fluid mx-auto" alt="Responsive image" width="170px"  height="270px" preserveAspectRatio="xMidYMid slice" focusable="false"></img>
                           
                        </div> 
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>

{% endblock content %}