core/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('update/', views.cart_update, name='cart_update'),
    path('del/', views.cart_del, name='cart_del'),
    path('add/', views.cart_add, name='cart_add'),
    path('', views.cart_summary, name='cart_summary'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('orders/', include('orders.urls', namespace='orders')), 
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('store.urls', namespace='store')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('search/', views.search, name='search'),
    path('create_product/', views.create_product ,name="create_product"),
    path('create_category/', views.create_category ,name="create_category"),
    path('<slug:slug>/', views.product_detail, name='product_detail'),  
    path('shop/<slug:slug>/', views.category_list, name='category_list'),
    path('rating/create_review/<slug:slug>/', views.create_review, name="create_review"),
]

core/store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.core.validators import MinValueValidator


class Category(models.Model):
    """ Rappresenta la categoria di un certo prodotto. """

    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories' 

    def get_absolute_url(self):
        """ Ritorna la lista dei prodotti per una certa categoria. """

        return reverse_lazy('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    """ Rappresenta un prodotto vendibile sull'e-commerce. """

    category    = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    title       = models.CharField(max_length=255)
    author      = models.CharField(max_length=255, default='Not found')
    description = models.TextField(blank=True)
    available   = models.PositiveIntegerField(default=1, validators=[MinValueValidator(0)])
    image       = models.ImageField(upload_to='images/', default='default.png') # salva il link nel database
    slug        = models.SlugField(max_length=255)
    price       = models.DecimalField(max_digits=4, decimal_places=2, default=4.50, validators=[MinValueValidator(1)])
    in_stock    = models.BooleanField(default=True)
    is_active   = models.BooleanField(default=True)
    created     = models.DateTimeField(auto_now_add=True) 
    updated     = models.DateTimeField(auto_now=True) 

    class Meta:
        ordering = ('-created',)

    def get_qty(self):
        """ Ritorna la quantita disponibile di un prodotto.  """

        return range(self.available)

    def get_absolute_url(self):
        """ Ritorna l'url di un prodotto per vederne il dettaglio. """

        return reverse_lazy('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title


RATE_CHOICES = [(1, '1 - Trash'), (2, '2 - Bad'), (3, '3 - Ok'), (4, '4 - Nice'), (5, '5 - Perfect')]

class Review(models.Model):
    """ Rappresenta una revisione. """
    
    user    = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date    = models.DateTimeField(auto_now_add=True)
    text    = models.TextField(blank=True)
    rate    = models.PositiveIntegerField(choices=RATE_CHOICES)
   
   
    def __str__(self):
        return self.text

core/store/forms.py
from django import forms

from .models import Category, Product, Review, RATE_CHOICES


class AddCategoryForm(forms.ModelForm):
    """ Reppresenta i campi da riempire per  creare una nuova Category """

    name = forms.CharField(label='Enter name', help_text='required', required=True)

    class Meta:
        model  = Category
        fields = {'name'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Name'})



class AddProductForm(forms.ModelForm):
    """ Rappresenta i campi da riempire per aggiungere un Product. """

    category    = forms.ModelChoiceField(queryset=Category.objects.all())
    title       = forms.CharField(label='Enter title', max_length=255, help_text='Required')
    author      = forms.CharField(initial="Not found", max_length=255, required=False)
    description = forms.Textarea()
    image       = forms.ImageField(initial="images/default.png")
    available   = forms.IntegerField(initial=1)
    price       = forms.DecimalField(max_digits=4, decimal_places=2, initial=4.50)
    
    

    class Meta:
        model  = Product
        fields = {'category', 'title', 'author', 'description', 'image', 'available', 'price'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Category'})
        self.fields['title'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Title'})
        self.fields['author'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Author'})
        self.fields['available'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Available'})
        self.fields['price'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Price'})



class AddReviewForm(forms.ModelForm):
    """ Rappresenta come compilare i campi per creare una Review. """

    text = forms.Textarea()
    rate = forms.ChoiceField(choices=RATE_CHOICES, required=True)

    class Meta:
        model  = Review
        fields = {'text', 'rate'}


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Text'})
        self.fields['rate'].widget.attrs.update({ 'class': 'form-control form-control-lg', 'placeholder': 'Rate'})

core/store/views.py
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Avg
import re

from account.models import UserBase
from orders.models import Order, OrderItem
from .forms import AddProductForm, AddCategoryForm, AddReviewForm
from .models import Category, Product, Review


def categories(request):
    """ Ritorna tutte le categorie nel database. """

    return { 'categories': Category.objects.all() }

def product_all(request): 
    """ 
        Ritorna tutti i prodotti nel database.
        Serve per la home page.
    """

    products = Product.objects.all()
    ctx = { 'products': products, 'recommend': recommend(request) }
    return render(request, template_name='store/home.html', context=ctx)

def all_reviews(request, slug):
    """ Ritorna le review per un certo prodotto """

    prod = Product.objects.get(slug=slug)
    reviews = Review.objects.filter(product=prod)
    
    
    ctx = {'reviews': reviews}
    return ctx

def product_detail(request, slug):
    """ 
        Ritorna in dettaglio un singolo prodotto.
        Oltre agli attributi di Product vengono passate le review di quel prodotto. 
    """

    product = get_object_or_404(Product, slug=slug)
    ctx = all_reviews(request=request,slug=slug)

    ctx.update({ 'product': product })
    return render(request, 'store/products/single.html', context=ctx)

def category_list(request,slug):
    """ Ritorna la lista di prodotti appartenenti a quella categoria. """

    category = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category=category)

    ctx = { 'category': category, 'products': products }
    return render(request, 'store/products/category.html', context=ctx)

@login_required
def create_product(request):
    """ 
        Crea un nuovo prodotto.
        Se invece il titolo e' di un prodotto gia' esistente allora ne cambia i dati.
        Solo un membro dello staff o dei venditori(seller) possono farlo.
        Se l'utente non appartiene ad uno dei due tipi di membro viene mandato alla home page.
    """  

    if not (request.user.is_staff or request.user.is_seller):
        return redirect('/')

    if request.method == 'POST':
        prodform = AddProductForm(request.POST, request.FILES)
        
        if prodform.is_valid():
            slug = re.sub('\W', '', prodform.cleaned_data['title'].lower())
            
            if not Product.objects.filter(slug=slug).exists():
                Product.objects.create(slug=slug, **prodform.cleaned_data)

            else:
                Product.objects.filter(slug=slug).update(**prodform.cleaned_data)

            if prodform.cleaned_data['available'] > 0:
                Product.objects.filter(slug=slug).update(in_stock=True)
            else:
                Product.objects.filter(slug=slug).update(in_stock=False)
                        
            return redirect('/')
    else:
        prodform = AddProductForm()
  
    return render(request, 'store/products/createprod.html', { 'form': prodform } )

@login_required
def create_category(request):
    """ 
        Crea una nuova categoria.
        Se esiste gia una categoria con quel nome allora redirecta l'utente alla home page.
        Come per create_product, solo un membro dello staff o un seller puo' creare nuove categorie.
    """

    if not (request.user.is_staff or request.user.is_seller):
        return redirect('/')

    if request.method == 'POST':
        catform = AddCategoryForm(request.POST)
        
        if catform.is_valid():
            name = catform.cleaned_data['name']
            slug = re.sub('\W', '', name.lower())
            
            if not Category.objects.filter(slug=slug).exists():
                Category.objects.create(slug=slug, name=name)
            
            return redirect('/')
    else:
        catform = AddCategoryForm()
  
    return render(request, 'store/products/createcat.html', { 'form': catform } )

@login_required
def create_review(request, slug):
    """ 
        Crea una nuova revisione.
        Solo un utente normalmente loggato puo' lasciare una review.
        Se un membro dello staff o un seller provano a farne una allora verranno redirezionati nella home page.
    """
        
    if request.user.is_staff or request.user.is_seller:
       return redirect('/')

    if request.method == 'POST':
        rateform = AddReviewForm(request.POST)
        
        if rateform.is_valid():
            product = Product.objects.get(slug=slug)
            usr = UserBase.objects.get(username=request.user)
            Review.objects.create(product=product, user=usr, date=datetime.now() ,**rateform.cleaned_data)
            
            return redirect(f'/{slug}/')
    else:
        rateform = AddReviewForm()
  
    return render(request, 'store/rating/home.html', { 'form': rateform, 'slug': slug } )

def search(request):
    """
        Viene fatta una ricerca della parola data in titolo, autore e descrizione per ogni prodotto.
        Viene inoltre cercato se la parola e' all'interno del nome della categoria.
        Se non viene passato nulla allora si viene redirezionati nella homepage.
    """
    
    word = request.GET.get('word')

    if not word :
        return redirect('/')

    prods = Product.objects.filter(slug__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")
    cats  = Category.objects.filter(slug__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")

    for cat in cats:
        prods |= Product.objects.filter(category=cat)

    prods |= Product.objects.filter(author__regex=r"(\w|\W)*( )*" + str(word) + "(\w|\W)*( )*")
    prods |= Product.objects.filter(description__regex=r"(\w|\W)*" + str(word) + "(\w|\W)*")

    ctx = { 'category': "Searched: " + word, 'products': prods }
    return render(request, 'store/products/category.html', context=ctx)

@login_required
def recommend(request):
    """
        La raccomandazione viene fatta vedere solo da utenti loggati.
        Per prima cosa vengono cercati tutti i prodotti con una media di piu di 2 stelle.
        Poi viene fatta una ricerca di tutti i prodotti comprati per capirne la categoria preferita
        e passare quindi i prodotti con quella categoria non ancora comprati.
    """

    products = list(Product.objects.filter(in_stock=True))
    prods = set()

    for product in products:
        if Review.objects.filter(product=product).exists():
            if Review.objects.filter(product=product).aggregate(Avg('rate'))['rate__avg'] > 2:
                prods.add(product)

    for order in Order.objects.filter(user=request.user):

        for oi in OrderItem.objects.filter(order=order) :
            p = Product.objects.get(title=oi.product)
                
            for product in Product.objects.filter(category=p.category, in_stock=True):
                prods.add(product)

        for oi in OrderItem.objects.filter(order=order) :
            prods.discard(oi.product)

    prods.discard(None)
    if not prods:
        prods = Product.objects.filter(in_stock=True).order_by('price')
        
    return { 'products': list(prods)[:6] }

core/templates/store/products/category.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
     {{category}}
    
{% endblock title %}


{% block content %}
<main>
    <div class="album py-5 bg-ligth">
        <div class="container">
            <div class="my-5 pb-5 h4">{{ category|capfirst }}</div>
            <div class="row row-cols-1 row-cols-sm-5 row-cols-md-6 g-3">
                {% for p in products %}
                    <div class="col">
                        <div class="card border-0">
            
                            <div class="card-body">
                                <p class="card-text">
                                    <a class="text-dark text-decoration-none" href="{{ p.get_absolute_url }}">{{ p.title|title }}</a>
                                    {% if not p.in_stock %} 
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="red" class="bi bi-exclamation-circle" viewBox="0 0 16 16">
                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"/>
                                        </svg>
                                    {% endif %}
                                </p>
                            </div>
                            <img class="img-fluid mx-auto" alt="Responsive image" src="{{ p.image.url }}"  width="170px"  height="270px"></img>

                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

core/templates/store/products/createcat.html
{% extends '../base.html' %}

{% block title %}Add{% endblock title %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 


{% block content %} 
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-md-12">
                <div class="login d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-lg-7  mx-auto">
                                <form class="account-form p-4 rounded col-lg-10 mx-auto" action="." method="post">
                                    {% csrf_token %}
                                    <h3 class="mb-4 py-5 text-center font-weight-bold">Create a new category</h3>

                                    <label>{{ form.name.label }}<span class="text-muted small"></span></label>
                                    {{ form.name }}      

                            
                                    <div class="text-center">
                                        <button class="btn btn-outline-success btn-block py-2 mb-1 mt-5 fw500 w-100" href="{% url 'store:create_category' %}">Save</button>
                                        <input type="hidden" name="next" value="{{ next }}"></input>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/store/products/createprod.html
{% extends '../base.html' %}

{% block title %}Add{% endblock title %} 

{% load crispy_forms_tags %} 
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 


{% block content %} 
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-md-12">
                <div class="login d-flex align-items-center py-5">
                    <div class="container">
                        <div class="row">
                            <div class="col-12 col-lg-7  mx-auto">
                                <form class="account-form p-4 rounded col-lg-10 mx-auto" action="." method="post" enctype="multipart/form-data">
                                    
                                    {% if form.errors %}
                                        {% for f in form %}
                                            {% for error in f.errors %}
                                                <div class="alert alert-danger" role="alert">{{f.label}}: {{error}}</div>
                                            {% endfor %}
                                        {% endfor %}
                                    {% endif %}
                                    
                                    {% csrf_token %}
                                    <h3 class="mb-4 py-5 text-center font-weight-bold">Create or change product</h3>

                                    <label>{{ form.category.label }}<span class="text-muted small"></span></label>
                                    {{ form.category }}      

                                    <label>{{ form.title.label }}<span class="text-muted small"></span></label>
                                    {{ form.title }}  
                                    
                                    <label>{{ form.author.label }}<span class="text-muted small"></span></label>
                                    {{ form.author }} 
                                    <br>    
                                    
                                    <label>{{ form.description.label }}<span class="text-muted small"></span></label>
                                    {{ form.description }}  
                                    <br><br>

                                    <label>{{ form.image.label }}<span class="text-muted small"></span></label>
                                    {{ form.image }}   
                                    <br><br>   

                                    <label>{{ form.available.label }}<span class="text-muted small"></span></label>
                                    {{ form.available }}      

                                    <label>{{ form.price.label }}<span class="text-muted small"></span></label>
                                    {{ form.price }}      



                                    <div class="text-center">
                                        <button class="btn btn-outline-success btn-block py-2 mb-1 mt-5 fw500 w-100" href="{% url 'store:create_product' %}">Save</button>
                                        <input type="hidden" name="next" value="{{ next }}"></input>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

core/templates/store/products/single.html
{% extends '../base.html' %}


{% block content %}
        <div class="container" style="max-width: 1000px">
            <main class="pt-5 my-5 pb-5">
                <div class="row g-3">
                    <div class="col-md-3 col-lg-5 order-md-first bg-white">
                        <img class="img-fluid mx-auto d-block" width="170px"  height="270px" alt="Responsive image" src="{{ product.image.url }}"></img>
                    </div>
                    
                    <div class="col-md-4 col-lg-7 ps-md-5 ps-lg-5">
                        <h1 class="mb-0 h4">{{ product.title|capfirst }}</h1>
                        <div class="row">
                            <div class="col-sm">
                                Author:
                                <span class="lead">{{ product.author|title }}</span>
                            </div>
                            <div class="col-sm">
        
                                Category:
                                <span class="lead">{{ product.category|capfirst }}</span>
                            </div>
                        </div>
                            
                        <div class="border">
                            <div class="col border-bottom">
                                <div class="row p-3">
                                    <div class="col-6">Prezzo</div>
                                    <div class="col-6 text-end"><span class="h4 fw-bold">{{ product.price }}€</span></div>
                                </div>
                            </div>
                            
                            {% if  product.in_stock %}
                                <div class="col">
                                    <div class="row p-3">
                                        <div class="col-6">
                                            <label for="select">Qty</label>
                                            <select id="select">
                                                {% for i in product.get_qty %}
                                                    <option value="">{{ i|add:1 }}</option>
                                                {% endfor %}  
                                            </select>
                                        </div>
                                        
                                        <div class="col text-end">
                                            {% if not user.is_staff and not user.is_seller %}
                                                <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-outline-success" >Add to cart</button>                 
                                                <a href="{% url 'store:create_review' product.slug %}" type="button" class="btn btn-outline-warning">Rate</a>
                                                                    
                                            {% endif %} 
                                        </div>  
                                    </div>
                                </div>
                            {% else %}
                                <div class="alert alert-danger" role="alert">
                                    This product is not available now
                                </div>
                            {% endif %}
                            
                            <p>{{ product.description|capfirst }}</p>      
                        </div>       
                    </div>
                    
                    <div class="my-5 pb-3 h4">Reviews</div>  
                               
                    {% for r in reviews %}
                        <div class="alert alert-secondary">
                            {{ r.user }}: {{ r.rate }}/5
                            <br>
                            {{ r.text }}
                            <br>
                            {{ r.date }}
                        </div>                                
                    {% endfor %}
                </div>
            </main>
        </div>

        <script>
            $(document).on('click', '#add-button', function (e)
            {
                e.preventDefault();
                $.ajax({
                        type: 'POST',
                        url: '{% url "cart:cart_add" %}',
                        data: { productid: $('#add-button').val(),
                                productqty: $('#select option:selected').text(),
                                csrfmiddlewaretoken: "{{ csrf_token }}",
                                action: 'post' },
                        success: function (json){ 
                                document.getElementById('cartqty').innerHTML = json.qty },
                        error: function (xhr, errmsg, err){}
                        });
            })
        </script>
{% endblock content %}